- name: Deploy on Swarm Cluster
  hosts: all
  gather_facts: False
  remote_user: ec2-user
  tasks:
    - name: Create a directory
      file:
        path: /home/ec2-user/deploy
        state: directory

    - name: Copy docker-compose.yml to master
      copy:
        src: docker-compose.yml
        dest: /home/ec2-user/deploy

    - name: Deploy on Swarm
      shell: cd infra-problem && docker stack deploy -c docker-compose.yml app
      register: stack_deploy

    - debug: var={{item}}
      with_items: stack_deploy.stdout_lines

    - name: Check list of services
      command: docker service ls
      register: service_list

    - debug: var={{item}}
      with_items: service_list.stdout_lines

    - name: Check list of stack
      command: docker stack ps infra
      register: stack_ps

    - debug: var={{item}}
      with_items: stack_ps.stdout_lines
